name: Verify Cypress

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run verify-cypress.sh script
      run: bash ./shell/verify-cypress.sh cypress/report/output.json

